spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/dev_db
    username: postgres-dev
    password: postgres-dev
  jpa:
    show-sql: true
    properties:
      hibernate-format-sql: true
logging:
  level:
    org.springframework.security: DEBUG